# Generated by Django 4.0.6 on 2022-07-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogspot',
            fields=[
                ('postal_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('headA', models.CharField(default='', max_length=500)),
                ('cheadA', models.CharField(default='', max_length=5000)),
                ('headB', models.CharField(default='', max_length=500)),
                ('cheadB', models.CharField(default='', max_length=5000)),
                ('headC', models.CharField(default='', max_length=500)),
                ('cheadC', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('images', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
